language: ruby

rvm:
  - 2.1.6
  - jruby-19mode
  - jruby-head

jdk:
  - openjdk6
  - openjdk7

services:
  - rabbitmq

sudo: false

cache: bundler

matrix:
  exclude:
    - rvm: 2.1.6
      jdk: openjdk7
    - rvm: 2.1.6
      jdk: oraclejdk7
    - rvm: jruby-head
      jdk: openjdk6
  allow_failures:
    - rvm: jruby-head
      jdk: openjdk7
