language: ruby

rvm:
  - 2.2.3

env:
  - DB=postgres

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate db:schema:load

after_script:
  - bundle_cache
